### ISSUE TITLE
The problem with Versus test suite

### ISSUE THREAD

**Issue by hamzaremmal** [versus-project/versus-app#248]
This issue sum up the actual problems with the test suite of Versus.

# Incorrect use of [IdelingResources](https://developer.android.com/training/testing/espresso/idling-resource)

Let check for example the following test [`OptionGetPlacesTest::testIfNoPlacesWithinRadius`](https://github.com/cs306-versus/versus-app/blob/7d32e3f2b2055221e7cb74291153e787226b7fe1/app/src/androidTest/java/com/github/versus/OptionGetPlacesTest.java#L182). 

- This test creates 2  instances of `ElapsedTimeIdlingResource` and **register** them. The problem here is : *We cannot register more  than IdlingResource with the same name*. (See [documentation](https://developer.android.com/reference/androidx/test/espresso/IdlingRegistry#register(androidx.test.espresso.IdlingResource...)))

- What if an assertion fail in a test ? The code that follows this assertion won't be executed. Therefore, the `IdlingResource` will never be *unregistered*. 

I believe that fixing this issues related to `IdlingResource` might fix the test suite and avoid the pseudo random behaviour the test suite has. 

> [Example project](https://github.com/android/testing-samples/tree/main/ui/espresso/IdlingResourceSample) using `IdlingResource` 

:information_source: This test was taken as an example because it failed most of the time.

**Comment by hamzaremmal** [comment]
@cs306-versus/dev, @cs306-versus/ta any thoughts ?

**Comment by hamzaremmal** [comment]
@Adam-GitHub0 and I agreed to remove those tests again and see the impact the have on running the CI.

If the distribution of the fails after 5 or 6 tries is still high, then we rule out those tests to be the problem (maybe partially the problem).

**Comment by hamzaremmal** [comment]
Build result [here](https://cirrus-ci.com/github/cs306-versus/versus-app/fix-location-tests)

- [First attempt](https://cirrus-ci.com/task/4880942746042368)  :+1:
- [Second attempt](https://cirrus-ci.com/task/5696682126475264) :-1:
> wait_for_avd
- [Third attempt](https://cirrus-ci.com/task/5521444004691968) :-1: 
> com.github.versus.ChatTest > testOnFirstPosition[emulator(AVD) - 11] FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@1175fa, window-token=android.view.ViewRootImpl$W@1175fa, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.GameFragmentTest > testGameFragment[emulator(AVD) - 11] FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@64d97fa, window-token=android.view.ViewRootImpl$W@64d97fa, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.ScheduleTest > testing[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing1[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing2[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing3[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing6[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testingNextWeeks1[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testingNextWeeks2[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testMakePost[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testCancelPost[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testScrollRecyclerView[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testSearchBar[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testPressProfile[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testScrollRecyclerView[emulator(AVD) - 11] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.TopGamesTest > testOnFirstPosition[emulator(AVD) - 11] FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@9d96c1b, window-token=android.view.ViewRootImpl$W@9d96c1b, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.TopGamesTest > testOnSecondPosition[emulator(AVD) - 11] FAILED 
- [Fourth attempt](https://cirrus-ci.com/task/5375678049157120) :-1: 
> com.github.versus.FsChatManagerTest > messageAdditionTest[emulator(AVD) - 11] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
com.github.versus.SearchFriendFragmentTest > testPressProfile[emulator(AVD) - 11] FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131362494/com.github.versus:id/view_profile>
	
com.github.versus.TopGamesTest > testOnSecondPosition[emulator(AVD) - 11] FAILED 
- [Fifth attempt](https://cirrus-ci.com/task/6649361841520640) :-1: 
> wait_for_avd
- [Sixth attempt](https://cirrus-ci.com/task/4667624605351936) :-1: 
> com.github.versus.ChatTest > testOnFirstPosition[emulator(AVD) - 11] 
FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@dd9b8de, window-token=android.view.ViewRootImpl$W@dd9b8de, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.GameFragmentTest > testGameFragment[emulator(AVD) - 11] 
FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@732dd85, window-token=android.view.ViewRootImpl$W@732dd85, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.ScheduleTest > testing[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing1[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing2[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing3[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testing6[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testingNextWeeks1[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.ScheduleTest > testingNextWeeks2[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testMakePost[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testCancelPost[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SeachFragmentTest > testScrollRecyclerView[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testSearchBar[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testPressProfile[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.SearchFriendFragmentTest > testScrollRecyclerView[emulator(AVD) - 11] 
FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
com.github.versus.TopGamesTest > testOnFirstPosition[emulator(AVD) - 11] 
FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@2f7b050, window-token=android.view.ViewRootImpl$W@2f7b050, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
com.github.versus.TopGamesTest > testOnSecondPosition[emulator(AVD) - 11] 
FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@aa7e57b, window-token=android.view.ViewRootImpl$W@aa7e57b, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
Tests on emulator(AVD) - 11 failed: There was 17 failure(s).


---

- 👍🏻 : 1
- 👎🏻 : 2
- wait_for_avd : 2

**Comment by hamzaremmal** [comment]
This might need to be fixed : https://cirrus-ci.com/task/5632197219057664
